apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: amarok-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    version: 2
spec:
  project: cluster-bootstrap
  repoURL: https://github.com/jellebens/argocd
  path: argocd
  targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true