apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.19.1
    helm:
      parameters:
        - name: crds.enabled
          value: 'true'
      tool: 
        helm:
          releaseName: cert-manager
    chart: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager