apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: cluster-bootstrap
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.28.0
    chart: base
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system